#!/usr/bin/env ruby
# frozen_string_literal: true

# Advent of Code 2021
#
# Robert Haines
#
# Public Domain

lib = ::File.expand_path('lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'aoc2021/extra/cli'

days = AOC2021::Extra::CLI.parse_params(ARGV)

unless days
  warn 'Usage: aoc-2021 <day>'
  exit 1
end

days.each do |day|
  AOC2021::Extra::CLI.run_day(day)
end
